name: Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  backend:
    defaults:
      run:
        working-directory: server/Ytc
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
      - name: Distribute
        run: ./gradlew distZip
